### ISSUE TITLE
Broken texture on part of the tail

### ISSUE THREAD

**Issue by Lykrast** [BuiltBrokenModding/SBM-Merpig#3]
![image](https://user-images.githubusercontent.com/8684850/51429274-55bb4680-1c0d-11e9-8f37-36a41f402d83.png)

The last segment of the tail before the fin has a misaligned texture, which makes a hole in it.

**Comment by DarkGuardsman** [comment]
Ya its been like that for a while... been too lazy to fix it. I think we have the updated model/texture... so it might already be fixed on the latest code.
