### ISSUE TITLE
Problem with the seagrass on a stick recipe in 1.12.2

### ISSUE THREAD

**Issue by ViltordX** [BuiltBrokenModding/SBM-Merpig#5]
I can't craft the seagrass on a stick. I tested it in creative, if i want to apply this mod in survival in the future. I tried it some variations, but i can't and no have recipe in the JEI either. When i check it in the JEI, then just combined with enhanched book pop up, what is strange. Why? As i did read, we can craft it with fishing rod plus a grass in 1.12. Then why can't i craft it? And i found in the mod in a recipe JSON file a fishing rod and a tall grass will be the seagrass on a stick. I tried with tall grass too in different shapes, but couldn't be crafted either. So idk what's the problem. Please help me, or fix it please in a new 1.12.2 version of the Merpig mod to work the recipe finally correctly! Thank you.

**Comment by DarkGuardsman** [comment]
Should be fixed in next release
