### ISSUE TITLE
Merpigs are spawning too frequently

### ISSUE THREAD

**Issue by Darkere** [BuiltBrokenModding/SBM-Merpig#7]
![image](https://user-images.githubusercontent.com/4283717/71995028-20eb3980-323a-11ea-88a4-46cc05aa9b94.png)

That seems a bit excessive. 

**Version** : SBM-Merpig-1.15.1-0.0.1
**Forge** : 1.15-30.0.30
**Pack** :  [Randomly Added Mods](https://www.curseforge.com/minecraft/modpacks/randomly-added-mods)

**Comment by bl4ckscor3** [comment]
You can adjust spawn weight and many other values related to spawning in the config.

**Comment by Darkere** [comment]
Ah my bad I saw on curseforge that that was a planned feature and didn't double check.

**Comment by Darkere** [comment]
Scratch that. I don't think we have enough options there. 

We just had 3000 merpigs with only 5 people online.

**Comment by bl4ckscor3** [comment]
Can't give you any more options as that is what Minecraft gives us.

**Comment by Darkere** [comment]
There is a mob cap for water mobs. Should those not be part of that?

**Comment by bl4ckscor3** [comment]
Minecraft should theoretically automatically do that, we classify the Merpig as a water creature in the code.
