### ISSUE TITLE
Spawnrate too high and Merpigs hovering above water

### ISSUE THREAD

**Issue by Areolata7** [BuiltBrokenModding/SBM-Merpig#8]
Using SBM-Merpig-1.14.4-0.0.1.jar. Love this mod but there are two annoying issues:

1. Default spawn rate is way too high. For example I have a small pond near my base which is about and it immediatly started with as many as 10 merpigs. I know you have planned a spawn rate config option but I really think the base setting should be lower. 

2. A lot of the time the Merpigs are levitating in the air space above the water. I known vanilla salmon/squid skim the top surface now and then but the merpigs are doing it a whole lot more. Also they are fully exiting the water not just gliding on the surface. I was boating the ocean recently and all of them (dozen) were hovering above the water. 

I took some images of the small pond near my base which shows numbers (in one I can see 8) and some levitating:

![2020-03-21_00 25 19](https://user-images.githubusercontent.com/56558824/77220145-4bdfec80-6b0b-11ea-8802-de44e170f238.png)
![2020-03-21_00 23 22](https://user-images.githubusercontent.com/56558824/77220135-35399580-6b0b-11ea-9852-a6082af81367.png)
![2020-03-21_00 25 04](https://user-images.githubusercontent.com/56558824/77220138-39fe4980-6b0b-11ea-90a7-44927cabdcd9.png)
![2020-03-21_00 25 10](https://user-images.githubusercontent.com/56558824/77220143-42ef1b00-6b0b-11ea-8279-1e234182237d.png)

**Comment by bl4ckscor3** [comment]
To 1.: There is a config option already.
